---
title: "Day 6"
output: html_document
date: "2024-12-06"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r Input}
data = c("......................#...#..............#.....................................#...#..............##..............................
......#.....#................#....#...........#........#......................#...............................#.....#.#.###..#...#
...#.#.................#........#.................#.........................................................#.....................
.....................................................................................................#.........#..................
.............................#.................#...................................#.....#....#........................#....#.....
..........................#.....................................................................#..#.............#................
.................#...........................#..........................#..............................#.#..#...................#.
..#....#....#......................................................................#....#.........................................
..................................#............#...........#...........................................#.#....#.............#.#...
...#...##....................................................................................#..........#..................#......
..................#.....#......#.....#...#.........#..#.............................#....##.............#...............##.#..#...
......#...............................................................................................................#..........#
...........#................................#.......#.............#...............#...................................#...........
............##...........................#........................................................................#...............
...............................#........#...#.................................#..#.#.............#...........#....................
........#..........#.#....................................................#........#....#..#.................................#....
.........#..............#........................#................................................................................
..................#..........................#.............#..................#.#...........#.....#...............................
...#...........#.#..........#.....................................................................................................
..............#.................#.....................................................................#...#......#.....#..........
..#.....#................................................................................................#.#.....#..........#.....
#.#..........#...#.............................#...............#..................................................#.#.............
..........................#..#.............#................................................................................#.....
...#..............................................................................................#..............#..#.......#.....
........................................#......#........................................#...................##...........#........
.............#..............#...........................##...#............#.....#..#..............................................
..#....#..#...............#........#.................#............................................#........##...............#.....
................................................#.......#...........##.............................#.##...........................
............................#..............#..#...........#...#.....#.#...................#.....#.............................#...
....................#....................................................................................#........................
.......................................................................................#.......................##..#..............
#.............................#.............................................................#............................#........
..............................................................................#.............#...#.........##......................
...............#..........................#.............#............#...........................................#................
................#........................#................................#...#............#.............................#........
..............................................................#.....#..........#.......#........#....#..................#.........
........................................................#..............................................................#.......#..
..#........#............#........#...#.....#.......#..............................................................................
..#..............#.#.....................................#..................................................#....##...............
............#........................#..........##.................................................................#........#.....
............#............#.#...............................................#.......#..............................................
..................#.........................................#............................#......#..................#...........#..
........................................................#.............##................................#........................#
.....................#...#......#.......#............#........#..................#...#.#....................................#.....
...........................................................................................#..............................#....#..
....#...................#.............#..........#..................................#.............................................
......................................#...............................................#..#........................................
.................#..#............................................#.............................................................#.#
............##...................................................................................#.........................#......
.........#.................................................#..#........................................#.....#..........#.....#...
.........#........................................................................................#.#...............#............#
..........#..#...........#...................#.....#.......#......#....#..#.......................#..........#..........#.........
......#...................................................#....#..............#....#.........##...#...............................
.........#........#........................#...........................................................#.......#................#.
.....................#...............................................#.##.........................................................
................................................................................#.............#..............#............#.......
......#..........#............................................#...#....................#...............................#.........#
......................................#....#.........#..............................................................#...#.........
.......##...#.#..........................................................#............#...........#........#...................#..
.....#............................................................................#............................#..................
....#..................#....#......#......#......................#......................#.......................................#.
..#..............#..#............#.................................#............#..................#................#.............
........................................................#....#...................................##.......................#.......
..........#..................................#....#........#.......#..........................#................#...............#..
.....................................#.................#..................#...........#...........................................
.........#..............#...................................................................................#...................#.
.................##.................................#.......#.......................................................#.........#...
...........#.................#..........................#...............................#..#...........................#..........
.....................................#...........................#...................#..............................#..#..........
.............................#.....#.................................................#.................##...............#.......#.
............#.........................................................................................................#...........
..........##.............#...................#.#...........................................#....................................##
..........#..#...#...............#........#........................................................#.................#............
....................#......................#....................................................#.#.....................#.........
.......................................#............#........................##............#....#..#..............................
..........#..........#.....................................#.................................#.......#............................
....#.............#...............................................................................................................
..#..............................................#....#......#........................................#.................#.........
...#......#.....#..............................#....#....................#......#..................#...................#.......#..
...............#..#...........................##..................................................................................
........#..#.....#.........................#.......#.............#..........................................#................#....
...#......#.............#...............#.............................................................................##..........
#.................................#.......#.........#.#.#...................................#...#.#...........#..........#........
#.........#....#...#.........#.#.............................................................#....................................
........................#.#.......#.................................................#.............................................
...#...##...#..#...........................#.....#..........................#...............................#.......#.............
................#..............................#..........##...................................................................#..
.......................................................................#...#..#...#.....#....#..................##..........#.....
#.....................#.........#........#.....................................................................#.....#.......#....
...........#......................#.......#.................................................#........................#............
.......#.........................................#.....#...#...........#................#....#......#...........#......#..........
....#.............#...............................#...#....#..#..#...........................................#.............#......
...#.........#..........................................#.....#...........^.#...#....#...........................#................
.....#..#...............#...........................#.#..........#........................................................#.......
.............#.......#.............................................................................................#...#..........
..#...................#...............................#......#............#...........#.......#...................................
...........#.......................#..........#...#.......................#..............#.............##.............#..#........
..#............#.............#.......................................................#.....##....................................#
.#.........#.....................................................................#.........#......................................
.............#....................................................................#.....#.............#...#...........#..........#
..........................#.....#...#......................#.................................#.....#.................#.......#....
..........#.#.....................................................................................................................
............#.......#....................#.......#.............................................#..................................
.......................................#..#........#...................................................#..........................
...................#........#....#........#..................#..........................................................#.........
........#..............#....................#............#......#...........#.....#..............................#.........#......
.......#.....#.................#.#..#..............................................................#.......#..#...........#......#
.#....................##.....................................................#...#.....#..........................................
...........#..................#.....#....#............#...............#....#............#.......................#.................
........#.....................................#......##............#..........................#..........#....................#...
..........................#...............................................................#.......................................
......................#..................................#.....................#.............................................#...#
.........#..............................................................#........##.........#.......#.............................
....#...#........#...........#....#.............#............#.....#..............................................................
...........#...............................................................................................#.......#..#...........
........#..........................#............................#...........#............#.............................#..........
.......#...........................#...#...............#..#..#...................#.........#......................................
..#..............................#........#...........#.......................................#...#...............................
.............#...#.............#.........#...........#.....................................#................#.....................
.........................#..........................#.................................#...........................................
..................##.............#........#......#............#........................#.......#......................#....#......
.....#............................................................................................................................
.#..................................#.....#.............#...#.............................................#..............#..##..#.
...............#........................................................#.........#..#..........#.........................#.......
.............................................#...................#.................#..................#......................#....
............................#.......................................................................................#.............
............#...............#....................#....#..........#..#..............................#......#.......#.......##......
............#.................................................................................#...................................
........................#...............................................................#......#.......#.......#.......###......#.
......................................#.#.........................................#.....#.............................#.........#.")
```

```{r Part 1}
data = c("....#.....\n
.........#\n
..........\n
..#.......\n
.......#..\n
..........\n
.#..^.....\n
........#.\n
#.........\n
......#...")
width = 130
data = str_split(data, "\n")[[1]]
data = strsplit(data, "")
data = matrix(unlist(data), byrow = T, ncol = width)

dt = data

boundary = T
direction = "up"
while (boundary == T) {
  position = which(dt == "^")
  row = position%%width
  col = as.integer(position/width) + 1
  position = c(row, col)
  
  if (direction == "up") {
    if (dt[row-1,col] =="#") {
      direction = "right"
    } else{ 
    dt[row,col] = "X"
    dt[row-1, col] = "^"
    }
  }
  
  if (direction == "right") {
    if (dt[row,col+1] == "#") {
      direction = "down"
    } else{ 
    dt[row,col] = "X"
    dt[row, col+1] = "^"
    }
  }
  
  if (direction == "down") {
    if (dt[row+1,col] =="#") {
      direction = "left"
    } else{ 
    dt[row,col] = "X"
    dt[row+1, col] = "^"
    }
  }
  
  if (direction == "left") {
    if (dt[row,col-1] =="#") {
      direction = "up"
    } else{ 
    dt[row,col] = "X"
    dt[row, col-1] = "^"
    }
  }

  if (1 %in% position | 130 %in% position) {
    boundary = F
  }
}

length(which(dt == "X"))+ 1
```

```{r Part 2}
library(parallel)
library(pbapply)

dt <- data
test <- dt
total_squares <- 16900
dt_length <- length(dt)
num_cores <- detectCores() - 1
answer <- 0

# Create a cluster
cl <- makeCluster(num_cores)

# Export variables to the cluster
clusterExport(cl, c("dt", "test", "width"))

# Progress-aware task function
process_square <- function(square) {
  dt <- test
  if (square != which(dt == "^")) {
    dt[square] <- "#"
  }
  boundary <- TRUE
  direction <- "up"
  count <- 0
  maxcount = 0
  local_answer <- 0
  
  while (boundary) {
    tryCatch({
      position = which(dt == "^")
      row = position%%width
      if (row == 0) {
        row = width
      }
      col = as.integer(position/width) + 1
      position = c(row, col)
      
      if (direction == "up") {
        if (dt[row-1,col] =="#") {
          direction = "right"
        } else{ 
          if (dt[row+1,col] == direction) {
            count = count + 1
          }
        dt[row,col] = "up"
        dt[row-1, col] = "^"
        }
      }
      
      if (direction == "right") {
        if (dt[row,col+1] == "#") {
          direction = "down"
        } else{ 
          if (dt[row,col-1] == direction) {
            count = count + 1
          }
        dt[row,col] = "right"
        dt[row, col+1] = "^"
        }
      }
      
      if (direction == "down") {
        if (dt[row+1,col] =="#") {
          direction = "left"
        } else{ 
          if (dt[row-1,col] == direction) {
            count = count + 1
          }
        dt[row,col] = "down"
        dt[row+1, col] = "^"
        }
      }
      
      if (direction == "left") {
        if (dt[row,col-1] =="#") {
          direction = "up"
        } else{ 
          if (dt[row,col+1] == direction) {
            count = count + 1
          }
        dt[row,col] = "left"
        dt[row, col-1] = "^"
        }
      }
    }, error = function(e) {})
    
    maxcount = maxcount + 1
    
    if (count > 10000 | maxcount > 16900) {
      boundary <- FALSE
      local_answer <- local_answer + 1
    }
    
    if (1 %in% position | width %in% position) {
      boundary <- FALSE
    }
  }
  return(local_answer)
}

# Run parallel processing with progress bar
results <- pblapply(1:dt_length, process_square, cl = cl)

# Stop the cluster
stopCluster(cl)

# Sum the results
answer <- sum(unlist(results))
cat("Final answer:", answer, "\n")
```

