---
title: "Day 12"
output: html_document
date: "2024-12-12"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r Input}
data = c("WWWWWWWHHHHHHHWHRRRRRJJBBJJGDDDDDDDDDDDDDDQQFFFFFFFFKFHHHHHEEEEEHHHKHHHHHHHUUUEEEEEEEEEEVVVVVVVVVVVRRRRRRRRUUUUNVVVVVVVVVVVVNNNNNNNNNNNNNYNN
WWWWWWWWHHHHHHHHRRRRJJJJJJJJDDDDDDDDDDDDDQQFFFFFFFFFFFHFHFEEEEEEHHHHHHHHHHHEUEEEEEEEEEEEVVDVVVVVRRRRRRRRRRRRUUUVVVVVVVVVVVVNNVNNNNNNNNNNNNNN
WWWWWWWHHHHHHHHHRRRJJJJJJJJDDDDDDDDDDDDDDDQFFFFFFFFFFFFFFFEEEEEEEHHHHHHHHHHEEEEEEEEEEEEEVVDVLVVLAARRRRRRRRRRUUUAVVVVVVVVVVVVVVNNNNNNNNNNNNNN
WWWWWWHHHHHHHHHHRRRRRJJJJJDDDDDDDDDDDDDDDDDDFFFFFFFFFFFFFFEEEEEEEHHHHHHHHHHEEEEEEEEEEEEEVVDVLLLLLLRRRRRRRRRUUUUVVVVVVVVVVVVVVNNNNNNNNNNNNNNN
WWWWWWWWWHHHHHHRRRRRJJJJJIDDDDDDDDDDDDDDDTTTFFFFFFFFFFFFFEEEEEEEEEIHHHHHHHHEEEEEEEEEEDTDVDDDDLLLLLRRRRRRRROOUUUVVVVVVVVVVVVVVNNNNNNNNNNNNNNN
WWWWWWWWWHHHHHHHRRRRJJJJJGYDDJDDDDDDDDVDDTTTFFFFFFFFFFFFFCEEEEEEEEEHHHHHHHHHEEEEEEEEEDDDDDDDDLLLLLRRRRRRRROOUUVVVVVVVVVVVVVNVNNNNNNNNNNNNNNN
WWWWWWWWWWWWHHRRRRRJJJJJXGYYGDDDDDDDDDDDTTTTFTTFFFFFFFFFFFFEEEEEEEEUUHHHHHHHEMMEEEEEDDDDDDDDDLLLLRRRRRRORROOUUVVVVVVVDVVVVVVVNNNNNNNNNNNNNNN
WWWWWWWWWWWBBRRRRRRRXXJJGGGGGGDDDVDDDDDTTTTPFTTFFFFFFFFFFFFEEEPPCCCCCCUHUUHSSMMEEEDDDDDDDDDDDLLLLTTRROROOOOOOUBBVVVDDDVVVVVVNNNNNNNNNNNNNNNN
WWYYWWWWWWWBBBRRRRRRRXXJAGGGGGGGDDDDDTTTTTTPTTTTTFFFFFFFFFEEEPPPCCCCCCCCCSSSSMMEEMMMMDDDDDDDDSLTTTTSTOOOOOOOOODDHDDDDDVVVVVVVVNNNNNNNNNNNPPP
YYYYYWWWWWBBBBBRRRRXXXXGGGGGGGGGGDDDDDTTTTTTTTTRFFFFFFFFFFEEEPPPCCCCCCCCCSSSSMMMMMMMMDDDDDDDDDLTTTTTTOOOOOOOOODDDDDDDDDVVVVVKKNNNNNNNNNPPPPP
YYYYWWWYBBBBBBBRRRRXXXXGGGGGGGGGGGGDDDQQQTTTTTTRRFFRFFFFFFFEPPPPCCCCCCCCCUUMMMMMMMMMMDDDDDDDDDLTTTTTTORORROROODDDDDDDDDDVVVVKKKNKNNNPPPPPPPP
YYYYYWYYDBBBZZBRRXXXXXXXXXGGGGGGGGGDDDQQTTTTTRRRRMFRFFFFFCCCCCCCCCCCCCCCCUUMMMMMMMMLLLDDDDDDDDDDTTTUTORORRRRRDDDDDDDDDDDVVVVKKKKKKPPPPPPPPPP
YYYYYYYYYBBBBBBRRXXXXXXXXXGGGGGGGGQDDQQQQQQTTRTRRRRRRFFFKCCCCCCCCCCCCCCCCUUUMMMMMMMLLLDDDDDDDDDSNTNTTORRRRRRRDUDDDDDDDDDVVKKKKKKKKKPPPPBBPPB
YYYYYYYYYYBBBBBXXXXXXXXXXXGGGGGGQQQQQQQQQQXTTTTRRRRRRFFFZCCCCCCCCCCCCCCCCUGUMMMMMMMLLLDDDDDDDDDDNNNNNORRRRPRRLUDDDDDDDDDKKKKKKKKKKPPPPPBBBBB
YYYYYYYYYYBBBBBXXXXXXXXXXGGGGGGQQQQQQQQQQQQTTTTTRRRRRSFFZCCCCCCCCCCCCCUUUGGMMMMMMMMLLLDDDDDDDDDDNNNNROORRRRRLLLLDLDDDDDKKKKKKKKKKKPPPPWBBBBI
YYYYYYYBBBBBBBBBXXXXXXXXXXGGGGGQQQQQQQQQQTTTTLRJRRRRRRRRZCCCCCCCCCCCCCCUGGGMMMMMMMMLLLDDDDDDDLDNNNNNRORRRRRRLLLLDLHDDDDKKKKKKKKKKKKPPPWBBBBB
YYYYYYYYBBBBBBXXXXXXXXXXXXXGGGGQQQQQQQQQQQTTTTRRRRRRRRRRRCCCCCCCCCCCCCCKGGGMMYYYMMMLLLDDDDDDDDNNNNNRRRRRRRRLLLLLLLLEDDKKKKKKKKKKKKKKPPWBBBBB
YYYYYYYBBBBBBBXXXXXXXXXXXXXGGGGQQQQQQQQQQRRRTRRRRRRRRRRRRCCCCCCCCCCCCCCKGGGGGYYYYYMLLLCDDDDDNNNNNNNNRRRRLRLLLLLLLLLEDDKKKKKKKKKKKWQQWWWBBBBB
YYYYYYYBBBBBBBXXXXXXXXXXGXXGGGGQQQQQQQDQQRRTTRRRRRRRRRRRRCCCCCCCCCCUCCCKZGGGYYYYYYMLLLDDDMMMMNNNNNNNNNULLLLLLLLLLLLEEDDKKKKKKKKKWWWWWWWWWBBB
LLYYYYYYBBBBBBXXXXXXXXXXGGGGGGGQQQQQQQDQQRRRRRRRRRRRRRRRRCCCCCCCCCCUUUKKZGGYRYYYYYYLLLMMDMMMMNNNNNNNLLLLLLLLLLLUULUEEDKKKKKKKKKWWWWWWWWWBBBB
IIYYYUYIIIIIBBBXXXXXXXXXMGGGGGGGQQQQQDDRRRRRRRRRMMRRRRRRRCCCCCCCCCCCCCCCZGGYYYYYYYUMMMMMMMMMMMNNNNNNLLLLLLLLLUUUUUUEUUKKKKKKWWWWWWWWWWWWBBBB
IIIIIIIIIIBBBBBBXXXXXMXMMGGGGGGGGGGGQUDDRRRRRRRMMMMMMRRRRRRRRUZCCCCCCCCCZZGYYYYYMYUMMMMMMMMMMNNNNNNNNNLLLLUULUUUUUUUUUKKKKBBJWWWWWWWWWWWBBBB
IIIIIIIIIIIIIMMBYXMMZZZZZZZGGGGGGGGGDUDDDDDRRRRRMMMMMMRRRRRRRUZCCCCCCCCCZGGYYYYYMMMMMMMMMMMMMNNNNNNNNNLLLOUUUUUUUUUUUUKKKBBBJJWWWWWWWWHWBBBB
IIIIIIIIIIIIIMMXXXXMZZZZZZZMGGGGGGGGDDDDDDDDRRRDDMMMMMRRRRRRJZZCCCCCCCCCZZGYYYYYMMMMMMMMMMMMMMNNNNNNNNNLLUUUUUUUUUUUPPBBKKBBJWWWBWWWWWHWBBBB
IIIIIIIIIIIIIMMMMMMMZZZZZZZMGGGGGXDDDDDDDDDDDDDDDMMMMMMRRRJJJZZCCCCCCCCCZZGGGGYYMMMMMMMMMMMMMMNNNNNNNNNNNUUUUUUUUUUUPPBBBBBBBBBWBNWWWWWWZBBB
IIIIIIIIIIIIIMMMMMMMZZZZZZZMGGGGXXXDDDDDDDDDDDVDMMMMMMMRRRJJJZZCCCCCCCCCZGGGGGGGMMMMMMMMMMMMMODDNNNNNNNNNNUUUUUUUUUUUPPBBBBBBBBBBNNNNNWUBBBB
IIIIIIIIIIIIIXMMMMMMZZZZZZZMMXXXXXDDDDDDDDDDDDDDMMMMMMMRRJJJZZZZZZZZZZSSSSSGGGGGMGMMMMMMMMMMMMMDNDNNNNNNNNUUUUUUUUUUPPPPPBBBBBBBBNNNNNNUBCCC
IIIIIIIIIIIIIXMMMMMMZZZZZZZMMXXXXXXDDDDDDDDDMMMMMMMMMMMMMJJJZZZZZZZZZSSSSSSSGGSGGGGMMMMMMCMMDDDDDDNNNNNNNNUUUUUUUUUUPPPPBBBBBBNBBNNNNNNNNCCC
IIIIIIIIIIIICMMMMMMMZZZZZZZMXXXXXXXXXDDDDDDDMMMMMMMMMMMJJJJJJJZZZZZZZSSSSSSSSSSSSGGMGGMMMMMMDDDDDDDYNNNNNNAAUUUUUUUUPPPPBBBBBBNNNNNNNNNNCCCC
IIIIIIIIIIFFMMMMMMMMZZZZZZZXXXXXXXXXDDDDDDDDDDDMMMMMMMMMJJJJJJZZZZZSSSSSSSSSSSSSSGGGGMMDDDDDDDDDYDDYNNNNNNAAAUUUUUUPPPPPBBBBNNNNNNNNNNNCCCCC
IIIIIIIIIIITTTTMMTMMZZZZZZZXXXXXXXXDDDDDDDDDDDDMMMMMMMMMJJJJJJZZZZZZSSSSSSSSSSSSGGSGGDDDDDDDDDDDYYYYNNNNNAAAUUUJJJUPPPPPPPPPNNNNNNNNNNNNNCCC
IIIIIIIIITTTTTTTTTTTTTXXXXXXXXXXXXXDDDDDDDDDDDDMMMMMMMMMMJJJJJZZZZZZZSSSSSSSSSSSSSSGGDDDDDDDDDDDYYYYYNNNNYYUUUUUJPPPPPPPPPPPNNNNNNNNNNNNNCCC
IIIIIIIIINTNTTTTTTTTTTXXXXXXXXXXXXDDDDDDDDDGDMMMMMMMMMMJJJJJJJZZZZZZGSUSSSSSSSSSSSGGGDDGDDDDDDDDDDJJJNNNNYYUUUUJJJPPPJPPPPPPPNNNNNNNNNNNNNCC
IIIIIIIIINNNTTTTTTTTTTXXXXXXXXXXXXJDDDDDNDGGMMMMMMMMMMMJMMMJJZZZZZZSSSSSSSSSSSSSSSGGGDAYYDDDDDDDDQQJJJJNYYYYYUUJJJJJJJVVPPPPPNNNNNNNNNNNNNCC
IIIIIIIIINNNNTTTTTTTTXXXXXXXXXXXXXDDDDDDGGGGMMMMMMMMMMMMMMJJJJJJZJZJSSSSSSSSSSSSGGGGGGYYYYDDDDMPPJJJJJJUYYYYYUJJJJJJJJPPPPPPRRRRNNNNNNNNCNCC
IIIIIIINNNNNNNTTTTTTTXXXXXXTXXXXXXDDDDDDDGGGGGMAAMMMMMMFMJJJJJJJJJJJSSSSSSSSSSSSSGGGYYYYYRDDDVMMMQQJJJJYYYYYJJJJJJJJJJPPPPPRRRRRRNNNNDNCCCCC
IIIIIINNNNNNNTTTTTTTTTTXXXXXCXXXXXDCTTGDGGGGGGGAAMMMMMMFMJEJJJJJJJJJJJJSSSSSSSSSGGGGYYYYYYDDDMMMMQQJJJJOYYYYYJJJJJJJJJJYPPPRRRRNNNNNNDNCCCCC
IIITTINNNNNNNTTTTTTTTTTTTWWWXXXXXXCCCTGGGGGGGGGAMMMMJMWEJJEJJJJJJJJIJJJSSSSSSSSSSGGGGYYYYYAAAAMMMMMYTTTYYYYCJJJJWJJJJJJJPPPRRRRRRRRNHHHCCCCC
IIIIIINNNNNNNNTTTTTTTTTTTTTTXXEXXXCCCCCGGGGGGAAAMJMJJJEEEEEEEEJJJIIIIIJSSSSSSSGSGGGYYYYYYYAAMMMMMMMYTTTYCCCCCJJJJJJJJJJJRRRRRRRRRHHHHHHHHCCC
IIIIIIIINNNNNNNTTTTTTTTTTTRRXHXXXXPCCDGGGGGGGAAJJJJJJJJEEEEEEEEJJIIIIIIIIISSSGGGGGYYYYYYYYAMMMMMMMYYTTTTCCCCCCJJJJJJJJJJJRRRHRHRHHHHHHHHHCCC
IIIIIIIINNNNNNTTTTTTTTTTARRRAHHHXXLLLLLLLGGGAAJJJJJJJJJJEEEEEEEJIIIIIIIIIIIISGGGYYYYYYYYYMMMMMMMMMYYYCTCCCCCJJJJJJJJJJJJRRRRHHHHHHHHHHHHHCCC
IIIIIINNNNNNNNTTTTTTTTTTARRRAAHHAVLLLLLLLLJJJJJJJJJJJJJJEEEEEEEJJIIIIIIIIIIISIGGYYYYYYYYYYMMMMMMMMMYYCCCCCCCCJJJJJJJJJJJRRRRRHHHHHHHHHHHHCCC
QIIIIINNNNNNNTTTTTTTTTTTAAAAAAAAALLLLLLLLLJYLJJJJSJJJJJEEEEEEEEJIINIIIIIIIIIIIIIYYYYYYYYYYMMMMMMMMMYYYCCCCCCCCJFFFFJJJJJRRRRRKHHHHHHHHHHHCCC
IIIIIINNNNNNNNTTTTTTTTTTAAAAAAAAAALLLLLLLLLLLJSSSSSSJJJJJEEEEEEJJJJIIIIIIIIIIIIIYYYYYYYYYYYYMMMMMMMNYYCCYCECCCCFFFZJJJJRRKKKRKKKHHHHHHHHHHCC
YIYIYYNNNNNNDDQTTTQQTTAAAAAAAAAAAALLLLLLLLLLLJVSSSSSSSSJJJJJJJJJJJJIIIIIIIIIIIIIYYYYYYYYYYYMMMMMMMMYYYYCYYCCCAAFFFZZZJJRKKKKRKKKHHHHHHHHHCCC
YYYYYYYYYNNNNNQQTQQQQTAAAAAAAAULLLLLLLLLLLLXLJVSSSSSSSJJJJJJJJJJJJJNNNNIIIIIIIIYYYYYYYYYYYMMMMMMMMMMYYYYYYCCCCCCFFFFJJJRKKKKKKKKHKHHHHHHHCCC
YYYYYYYYNNKKKWQQQQQQQTAAAAAAAAULLLLLLLLLLLLLLVVSSSSSSJJJJJJJJJJJNNNNNNNNIIIIIIIYYYYYYYYYGQQQQMMMMMMMYYYYYCCCCRRCFFFFFFJRKKKKKKKKKKKKHHRCCCCC
YYYYYYYYYNKKKKQQQRRRAAAAAAAAAAAAAAALLLLLLLLLVVSSSSSSSSSJJJJJJJJJNNNNNNNNIIIIIIIIIYYYYYGGGGQQQQMMMMMYYYYYYYYCCCRRFFFFFTTKKKKKKKKUKKKKHRRCCCCC
YYYYYYYYYYKKKKKKQQRRAAAAAAAAAAAAAAALLLLLLLLLVVVSSSSSSJJJJJJJJJJJNNNNNNNNNIIIIIIIIGYGYGGGGQQQQQMMMMYYYYYYYYYCCYFRFFKKKTKKKKKKKKKKKKKKKRRRCCCC
YYYYYYYYKKKKKKKQQRRRAAAAAAAAAAAAAAALLLLLLLXLXXSSSSSSSJJJJJJJJJJJJNNNNNNINIIIIIIIIGGGGGGGQQQQQQMMMYYYYYYYYYYYYYFFFFKKKKKKKKKKKKKKKKKRKKRRRCCC
YYYYYYYYKKKKKKKKPRRRRRWAAAAAAAAAAZZLLLLLLLXXXXSSSSSSMSJJSSJJJJJJJNNNNNNIIIIIIIIIIIGGGGGGGGGGQQGYYYYYYYYYYYYYYYFFFFFKKKKKKKKKKKKKKKKRRRRRRCCC
YYYYYIIYKKKKKKKPPRRRRAAAAAAAAARRAZZLLLLLLLXXXSSSSSSSSSSSSSJSJJJJNNNNNNNNIIIIIIIIIIGGGGGGGGGGQGGYYYYVVYYYYYYYYFFFFFFFKKKKKKKKKKKKRRKRRRRRRRRC
YYIIIIIYKKKKKKKPPRRRRRAAAAARRARAAAALCCLLLLXXXXSSSSSSESSSSSSSSSJJNNNNNNNNXXIIIIIIIIIGGGGGGGGGGGYYYYVVVVYVVYYYYKKKKKKKKKKSKKKKKKKKRRKRRRRRRCCC
IIIIIIIIIIIIKYRPRRRRRRAARARRRRRARACCCCLLLLXXXXSSTSSSSSSSSSSSSJJJJNNNNXXXXXXIIIIIIIIGGGGGGGGWWWWWWYVVVVVVVYKKKKKKKKKKKKKSKKKSSKSKRRRRRRRRRCCP
IIIIMIIIIIIIIRRRRRRRRRRRRRRRRRRRRGCCCGGLLLXXXXXTTSSSSSSSSSSSSJJJNNNNXXXXJJJJIIIIIIIGGGGGGGGWWWWWWYVVVVVVVVKKKKKKKKKKKKKSKKSSSSSSSRRRRRRRRCCP
IIIMMMIIIIIIRRRRRRRRRRRRRRRRRRRGGGCCCGGRRRQXQQXTSSSSSSSSSSSSSOOJJNXXXXXJJJJJIIIIIGGGGGGGGGGWWWWWWYVVVVVVVUKKKKKKKKKKKKKSKKSSSUSSRRRRRRRRRRPP
MMMMMMIIIIIIIIIRIRRRRRRRRRRRRRRGGGGGGGGRRQQQQYQQSSSSSSSSSSSSOOOCOOXXXXXXXJJJJIIIIIGGGGGGGGWWWWWWWQVVVVVVVVKKKKKKKKKKKKKSSSSSSSSRRRRRRRRRPPPP
MJJMMMMMIIIIIIIIIIIGRRRRRRRRRGGGGGGGGQRRQQQQQQQQQQSSSSSSSSOOOOOOOOXXXXXJJJJJAIIIIIIGGGGGGGGWWWWWWQVVVVVVVUKKKKKKKKKKKKKKKKKKSSRRRRRRRRRPPPPP
MMMMMMMMIIIIIIIIIIIGGRRRRRRRGGGGGGGGGQQQQQQQQQQQQQQSSSSSSSOOOOOOOOOXXXXJJJJJAIIIIIIIIVVVGGVWWWWWWVVVVVVVVVVZZKKKKKKKKKKKKKKKSSSRRRRRRRPPPPPP
UUUUMMMMIIIIIIIIIIGGGGGGGRRRGGGGGGGGGQQQQQQQQQQQQQSSSSSSSSOOOOOOOOXXXXXXJXXJAIIIIIAAIIVVVVVWWWWWWVVVVVVVVVVZZKKKKKKKKKKKKKKKDDSSDDRPRRPPPPPP
UUUMMMMMMMIIIIIIIIGGGGGGRRRGGGGGGGGGQQQQQQQQQQQQQQSSSSSSSSOOOOOOOXXXXXXXXXXXXRRIIIAAIIVVVVVWWWWWWVVVVVVVVVVZZKKKKKKKKKKKKKKKDDDPPDPPPPPPPPPP
UUUMMMMMMMMMIIIIIIIGRRGRRGRRGGGGGGGQQEQQQQQQQQQQQQQSSSSSSSOOOOOOOOOXXXXXXXXXXRAAAIAAVVVVVVVWWWWWWVVVVVVVVVVZZZZZZGKKKKKKKKKKDDDPPPPPPPPPPPPP
UUUMMMMMMMMMMMMIIIIGGGGGGGGGGGGGGGGQQGSQQQQQQQQQQQQSSSSSSSOOOOOOOOXXXXXXXXXXPAAAAAAAAVVVVVVWWWWWWVVVVVVVVVVZZZZGZZKKKKKKKKKKDDDDPPPPPPPPPPPP
UUUMVAMMMMMMMMMIIIIGGGGGGGGGGGGGGGGGGGQQQQQQQQQQQQQQQSSSSOOOOOOOOOOXXXXXXTXXPAAAAAAAVVAVVVVVVVVVVVVVVVVVVVVZZZGGGGKKKKKKKKKKDDPDPPPPPPPPPPPQ
UUUVVAMMMVVVMMMIIGGGGGGGGGGGGGGGGGGGGGGWQQQQQQQQQQQQQSSSSOOOOOOOOOVXXXUUTTTXPAAAAAAAAAAVVVVVVVVVVVVVVVVVVVVVGGGGGGKKKKKKKKKKDDPPPPPPPPPPPPPP
UUUVVAVMVVVVVMAAGGGGGGGGGGGGGGGGGGGGGGGWWWQQQQQQQQQQQSSSSOMOOOOOOOOOOXUUUUTTAAAAAAAAAAVVVVVVVVVVVVVVHVVVVVVVFGGGGGKKKKKKKKKKZDDPPPPPPPPPPPPV
UUUVVVVVVVVVVAAKKGGGGGGGGGGGGGGGGGGGGGGGWQQQQQQQQQQQQSSSSMMMMOMMOOOOXXXXUUUTAAAAAAAAAAAVVVVVVVVVVVCHHHHHHUUUHGGGGGGZZZZZZZZZZDPPPPVPPPPPVVPV
UUUUVVVVVVVVVVKKKKKTGGGGGGGGGMGGGGGGGGGQQQQQQQQBQQQIQSSSMMMMMMMMMMMOXXUUUUUUUAAAAAAAAAAAVVVVVVVVGHHHHHHHHUHHHHGGGGGZZZNZZZZZZZVVVVVPPPVPVVVV
UUVVVVVVVVVVKKKKKKKGGGGGGGGGGGGBBBBBGGQQQQQQQQQQQIIIQSIIMMMIMMMMMUUUUUUUUUUUSSSAAAAAAAAAWWVXVVVVGHHHHHHHHHHHHHGGGZZZZZZZZZZZZZZVVVVVPPVVVVVV
UUVVVVVVVVVVKKKKKKKKRGGGGGGGGBBBBBBBGGQQQQQQQQQQQIIIIIIIIIIIIMMMUUUUUUUUUUUUSSSSAAAAAAAAWVVVVVVLHHHHHHHHHHHHHGGGAZZZZZZZZZZZZZZVVVVVVVVVVVVV
MUUMVVMOOVVWWWKKKKKKRRGGGGGGGGBBBBBBBGQQQQQQQQQQQQIIIIIIIIIIMMMMUUUUUUUUUUUUUSSSSSAAAAAJVVVVVVLLHHHHHHHHHHHHGGGZZZZZZZZZZZZZZAAVVVVVVVVVVVVV
MUMMMMMMMMVWWKKKKKKKKGGBBBGGBBBBBBBQQQQQQQQQQQQQQQIIIIIIIIIMMMMMMUUUUUUUUUUUSSSSSSSAAAJJJVVLLLLLHHHHHHHHHHGGGGGZZZZZZZZZZZZUAAAAVVAVAAVVVVVV
MMMMMMMMMWWWWWKKXKKKUUGZBBBBBBBBBBBBBBBEQQQQQQQQQQQIIIIIIIIMMMMUUUUUUUUUUUUSSSSSSSSSSFFFFTVLLLLLLLZHXZHCHHHHGGGGGZZZZZZZZZZZAAAAAAAAAAVVVVVV
MMMMMMMMMMMWWWKXXXUUUUXZZBBBBBBBBBBBBBBBQQQQQQQQQQQIIBIIIIIMMMMUMUUUUUUUUUUSSSSSSSSSSFFFTTFFLLLLZLZZZZZCHGGHGGGGGGZZZZZZZZZAYYAAAAAAAAAVVVVV
MMMMMMMMMMMWWWXXXUUUXXXZZBBBBBBBBBBBBBBBQQQQQQBBBQBIIBIIMMMMMMMMMUUUUUUUUUUSSSSSSSFFFFFFFFFLLLLZZZZZZZZZZGGGGGGGGGZZZZZZZZAAYAAAAAAAMAVVVVVV
MZZZZZZZZMMMWWXXXUXXXXXBBBBBBBBBBBBBBBBBBBQQQQQQBBBIBBBMMMMMMMMMUUUUUUUUUUUUUSSSSLGFFFFFLLLLLLLLZZZZZZZZLGGGGGGGGGGZZZZZZZAAAAAAAAAAAAVAVVVV
AZZZZZZZZFFFXXXXXXXXXXXXBBBBBBBBBBBBBBBBBBBBEEBBBBBBBBMMMMMMMMMMUUUUUUUUUUUUUSHSSLLLFFFFFLLLLLLZZZZZZZZZLGQQGGGGGGGZZZZZZAAAAAAAAAAAAAAAAVVV
AZZZZZZZZZZZZXXXXXXXXXXXBBBBBBBBBBBBBBBBBBSEEEEEBBBBBBBMMBBMMMMMMUUUUUUUUUUUUUHHHSLLFPPFLLLLLLLZZZZZZZZZZQQGGGGGSSZZZGZZGAAAAAAAAAAAAAAAXVVV
AZZZZZZZZZZZZFFXXXXXXXXXBBBXBBXXXBBXXBBBXXEEEEEEEBBBBBGMBBBMMMMMUUUUUUUUTUUUUTHHHSLLPPPFLLLLLLZZZZZZZNNNNNNNNNNSSSZGZGGGGAGGGGAAAAAAAAAAAVVV
AZZZZZZZZZZZZXXXXXXXXXXXBBXXXBXXXXXXXBBXXAEEEEEEEBBBGGGGGBBMMBMMUUUUUUUUUUUUHHHHHHLLLLLFLLLUUUMZUZZZZNNNNNNNNNNSSSGGGGGGGGGGGGAAAAAAAAAAJJVV
AZZZZZZZZZZZZSSXXXXXXXXXXXXXXXXXXXXXXXXXAAEEEEEEEEBGGGGGGGBMBBMMGGGUUXUUUUUUHHHHLLLLLLLLLLUUUUUUUUHHZNNNNNNNNNNSGGGGGGGGGGGGGGAAAAAAAAAAAVVV
AZZZZZZZZZZZZSSHHHHXXXXXXGGGGXXGGXXXXXAAAAEEEEEEBBBGGGGGGGBBBBBMMMUUUUUUUWWUHPPHWLLLLLLLLLUUUUUUUUHHZNNNNNNNNNNSGGGGGGGGGGGGGGAAAAAAAAALVVVV
AZZZZZZZZZZZZSSHIHHHHHHHXXGGGGGGGGXXXXAAAAAEEEEEEGGGGGGGGGGBBBBBBUUUUUUUUWWUHHHHWWLLLLLLUUUUUUUUUUHHZNNNNNNNNNNYYGGGGGGGGGGGGGAYAAAAGAALVVVV
AZZZZZZZZZZZZZZZZHHHHHHXXGGGGGGGXXXXXAAAAAAEEEEEEGGGGGGGGCBBCBBBBBBUUUUUUTWWWHWWWWLLLLLLRUUUUUUUHHHHZNNNNNNNNNNYYYYGGGGGGGGGGGQYAAAAGALLVVVL
AZZZZZZZZZZZZZZZZIHHHHHGGGGGGGGGXGGXGAAAAAAAEKEEEGGGGGGGYCBBCCCBBBBUUUUUUTWWWWWXXWLLLLLLNNNNNNNNNNNNNNNNNNNNNNNYYXXXGGBBGGGGGGQQGGAAGAALLLLL
AZZZZZZZZZZZZZZZZZZZZZZZZGGGGGGGGGGGGAAAAAAAAAMMMMMGGGGGCCCCCCBBBBBAAAUUUTWWTWWWXXXOOOOVNNNNNNNNNNNNNNNNNNNNNNNYYXXXXXQBGGGGGGQAAGGGGGGLLLLL
AZZZZZZZZZZZZZZZZZZZZZZZZGGGGGGGGGGGGAAAAAAAAMMMGGGGGGCCCCCCCCBBBBBBBAUUUTWTTWXWXXVOOOOONNNNNNNNNNNNNNNNNNNNNNNNNXXXXXQGGQQGGQQAAGGGGAGGLLLL
AZZZZZZZZZZIIIIZZZZZZZZZZGGGGGGRRGGKGAAAAAAAAMMMGMGGTGVVCCCCCCCCBAAAAAAUUTTTTTXXXOVVOOOOOHUUUUHNNNNNNNNNNNNNNNNNNXXXXXQQQQQQGQAAAGGGGAGGLLLL
AZZZZZZZZZZIIIIZZZZZZZZZZGGGGGGRBBRKGAAAAAAAAAMMMMTTTGVVCCCCCCCCBBBAAAAUUTTTTTTXXOOOOOOOOOKUUUHNNNNNNNNNNNNNNNNNNXXXQQQQQQQQQQAAAGGGAALLLLLL
AAAAAAAACIIIIIIZZZZZZZZZZGGEGRRRRRRRAAAAAAAAAAMMMMMMTGGGCCCCCCCCBBBAAAATTTTTTTTTTOOOOOOOOKKKUPPPPHPHHHHHNNNNNNNNNXXQQQQQQQQQQQQAAAAAAAALLLLL
AAAAAAAAAQQIIIIZZZZZZZZZZGGEEERRRRRAAAAAAAAMMMMMMTMTTTTTCCCCCCCCCCBAAAAQQTTTTTTTOCOOOOOOOKKKPPPPPPPHHPHHNNNNNNNNNNNNQQQQQQQQQQQQQQAAAAAAAALL
AAAAAAAAAQQIIIIZZZZZZZZZZEEEEEERRMMAMMAAAPAMMMMMMTTTTTTTCCCCCCCCAAAAAAQQQTTTTTTTOOOOOOOOOKKPPPPPPPPPPPPLNNNNNNNNNNNNQQQQQQQQQQQQQQAAAAAAAAAA
AAAAAAAAAQQIIIIZZZZZZZZZZEEEEEERRMMMMMAAAAMMMMMTTTTTTTTTGCCCCCCCAIIAAATTTTTTTTTTOOOOOOOOOOOHPPPPPPPPPPPPPPNNNNNNNNNNQQQQQQQQQQQAQAAAAAAAAAAA
AAAAAAAQQQQQQIIZZZZZZZZZZEEEEEEEEMMMMMMAMMMMMMTTTTTTTTTTTTDDTIIIIIIAARTTTTTTTTTTOOOOOOOOOHHHPPPPPPPPPPPPPPXXXBBBBEBBGBBQBQBQQQQAQAAAAAAAAAAA
EAAGASSPQQQQQQIZZZZZZZZZZEEEEEEMMMMMDMMMMDMMMMMTTTTTTTTTTTTTTTIIIIAAARTTTTTTTTOOOOOOOOOOHHHPPPXPPPPPPXXXXXXXBBBBBBBBBBBBBBBQQQQAAAAAAAAAAAAA
EAAGPPSPPPPQQQQQQQEEEQQEEEEEEEEEMMDMDMMDDDDMMMMTTTTTTTTTTTTTTIIIIIIAITTTIITTTLLOOOOOOOOOYYYMMMPPPPPPPXXXXXXBBBBBBBBBBBBBBBBQQQQAAAAAAAAAAAAA
EPAPPPPPPPPPQQUQQQEEEEEEEEEEEEEMMMDDDDDDDDDMMMTTTTTTTTTTTTTTIIIIIIIIIIIIIITTTTLLOOLLYYOYYYYYYPPPPPPMPXXXXXXBBBBBBBBBBBBBBBQQQQQKAACCAAAXAAAA
PPSPPPPPPPPAUUUQQQEEEEEEEEEEEEEMMMMDDDDDDDDDTTTTHTTTTTTTTTTTIIPIIIIIIIIILIIILLLLLJLLLYYYYYYYPPNNPPPMXXXXXXXBBBBBBBBBBBBBBPPQQQQAACCCAAAAAAAA
PPPPPPPPPPPPUUUQEEETTEEEEEEEEEMMMMDDDDDDDDDDTUEPTTTTTTTTTTTTIIPPIPIPIIIILLILLLLLLLLLLLYYYYYYYPPPPPPXXXXXXXBBBBBBBBBBBBBBBBBQQQCCCCCCAACAAKKU
PPPPPPPPPUPUUUEEDEETTTEEEEEEEEMMMMMDDDDDDDDDNEEEKTTTTTTTTTTPPPPPPPPPIIIILLLLLLLLLLLLLLYYYYYYYMZPPZZZXXXXXXBBPPPBBBBBBBBBBNNPPPCCCCCCACCCKKKU
PPPPPPPPUUPUUEEEEEEEEEMEENXXEEMXMDDDDDDDDDDDDDEKKJTTTTWTTTTPPPPIIIIIIIIIIILLLLLLLLLLLLYYYYYQQYZZPZZZZZZXXXPPPPPPBBBBBBBBBNNNPPPPCCCCCCCCCCCC
PPPPPPPPPUUUUEEEEEEEEEEEEXXXXXXXXDDDDDDDDDDDDEEEJJVTTWWTTTPPPPPPPIIIIIIIIILLLLLLLLLLLLYYYYYYYYYZPZZZZZZZXZEPPEEPBBBBBNBBNNNNPPPPPPPCCCCCCCCC
PPPPPPPPUUUEEEEEEEEEEEEAAXXXXXXXXXDDDDDDDDDDDEEELJJJJWWTWTYYPPPPIIIIIIIIIQLLLKKLLLLLLLYYYYYYYYYZZZZZZZZZZZEEEEEEEBBNNNNNNNNNPPPPPPPCCCCCCCCC
PPPPPPPUUUUUUEEEEEEEEEEAAXXXXXXXMMDDDDDDDDDDDEEEJJJJWWWWWPPPHPPPPPIIIIIQQQQKKKKLLLYYYYYYYYYYYYYYZZZZZZZZZEEEEEEEEEBNFFNPPPPPPPPPPPPPPCCCCCCC
PPPPPPUUUUUUUEEEEEEEEEAAAXXXXXXXXXDDDDDDDDDDDEEEJJJJJJWWWPPPPPPPPPPPIIIIQQQQKKKKLEYYYYYYYYYYZZZZZZZZZZZZZZZZGEEEEAFFFFNPPPPPPPPPPPPPPPPCCCCC
PPPPPPJJUUUUUUUEEEEEEAAAAXXXXXXXXXBDDDDDDDDDEEJJJJJJWWWWWPPPPPPPPPPPPIIQQKQQKKKKBBYYYYYYYYFFZZZZRZZZZZZZZZZZZEEEFFFFFNNNPPPPPPPPPPPPPPPCCCCR
PPPPPRJJJJJUUUUEEEEEEEAAXXXXXXXXXXBDDDDIDDDEEEJJJEJJWWWWWPPPPPPPPPPPIIIIQKKQKBKKBBYYFFYYYYFZZZZZRRZZZZZZZHZZZHEFFFFFFFFPPPPPPPPPPPPPPPCCCCCR
KKPPPRRRJCCUUUUUEEEEEEAAXXXXXXXXXXXXDDDKWDDDEEJJJEJJWWWWWWWPPPPPFPPPPIDDKKKKKBBBBBYYYFYYYFFFZZZZZRZZZZZZZHZHHHHFFFFFFFFFPPPPPPJPPPPPPPPCCCRR
KKPPPGGGJJCUUUUUEEEEEEAXXXXXXKKKXXXXKJKKKEEEEEJJEEJJWWFWWWPPWPPPPPPPPIDDKKBBKBBBBBFFYFYYFFFFZZZZZRZZZYZHHHHHHHFFFFFFFFFFEQPPPPCPPPCPPCCCRCRR
KKPPGGGGJJCUUUUUEEUUUUXXXXXBBKOKKKKKKKKKEEEEEEEEEEFKFFFFWWPPWPPPPPPWDDDDKKBBBBBBBBFFFFYFFFFFZZOZZRZZZYHHYYHHHHCCCFFFFZFEEQQCCCCPCCCPCCCCRRRR
GGGGGGGGCCCCUUUUUEUUUUUUUUXBBKKKKKKKKKKKEEEEEEEEEEFFFFFFWWPWWPPPPPPWDDDKKKKBBBBBBBFFFFFFFFFFFZOZZHZZYYHYYYYYHHCCCCFFFOOEEQQQQQCCCCCCCCCCRFRR
NGGGGGGGCCCCOUUUUUUUUUUUUUXBBKKKKKKKKKKKEEEEEEEEEFFFFFFFWWWWWPWPPWWWDDDKKKKBBBBBBBBFBFFFFFFFFFHHHHYYYYYYYYYYCCCCCCCCOOOEQQQQQQCCCCCCCCFFFFFR
NGGGGGGGCCCCOOUUUUUUUUUUUBBBBBKKKKKKKKKKEEEEEEEEEFFFFFFWWWWWWWWPWWDDDDDDDKBBBBBBBBBBBBBFFFFFFFHHHHYYYYYYYYYYYCCCCCOOOOQQQQQQQQCCCCCCCFFBFFFF
GGGGGGGCCCOOOOOOUUUUUUUUUBBBBKKKKKKKKKKRKEEEEEEFFFFFFFFFFWWWWWWWWWWDDDDDKKBJBBBBBBBBBBFFFFFFFFFHHHYYYYYYYYYCCCCOOOOOOOQQQQQQQQQCCCCCFFFFFFFF
GGGGGGGCCCCOOOOOUUUUUUUUBBBBBKKKKKKKKKKKKEEEEEEFFFFFFFFFFWWWWWZZWTTDDDDDDKBBBBBBBBBBFFFFFFFFFFFFHHHYYOOOYYYCCCCCOOOOOQQQQQQQQGGCCCCCFFFFFFFF
GGGGGGGGGCCOOOOOOOOOUBUUUBBBBBBKKKKKKKKKKEEEEFFFFFFFFFFFFZZZZZZZTTTTDDDDBBBBBBBBBBBFFFFFFFFFFFFHHHHHHHHHCCCCCOOOOOOOOQQQQQQQQGCCCCCCFFFFFFFF
ZGIGGIJGCCCOOOOOOOOOBBUBBBBOBBKKKKKKKKKKKEEEEEFFFFFFFFFFFZZZZZZZTTTTDTDWWBWBBBBBBBFFFFFFFFFFFFFSFHHHHHHHHDCCCOOOOOOOOQQQFFQQQQACCCCCCPPFFFFP
IIIIIIIICCOOOOOOOOOOBBBBOBOOOKKKKKKKKKKKKEEEEEFFFFFFFFFFZZZZZZZTTTTTTTWWWWWBBFBBBBFFFFFFFFFFFFFFFHHHHHHBHCCCAAAOOOOOOOOOQQQQQQCCCCCCCCPPPPPP
IIIIIIICCCOOOOOOOOOOOBBIOBBOOOOXKKKKKKKKKKEEEFFFFFFFFFFKZZZZZZZPPPTTTTTWWWWWBFBBBBFFFFFFFFFFFFFHHHHHHHHHHCCCCCOOOOOOOOOOOQQQQACCCCCSCCPPPPPP
IIIIIIICCCOOOOOOOIOIIBIIOOOOOOOXKKKKKKKKKKEEEFFFFBBFFFFFZZZZZZZZPPTPTPTWWWWWFFFFBFJJFFFFFFFFFFFHHHHHHHHHHHCWWMOOOOOOOOOOOQQAAACCCYCCCPPPPPPP
IIIIIIICCCCOOOOOIIIIIIIIIOOOOOOOKKKKKKKKKKEEEFFFFFBBBFBZTZZZZZZJPPPPPPPWWWFWFFFFFFFFFFFFFFFFFFFFFFHHHHXHHWWWMMMOOOOOOOOOOOCACACCCYCCPPPPPPPP
IIIIIIIICCOOOOOIIIIIIIIIIOOOOOOKKMKKHKHKKKKKEFEZFFBBBFBZZZZZZZZPPPPPPPPPPWFFFFFFFFFFFFFFFFFFFFFFFFHHHXXXXWWMMMMMOOOOOOOOOOCCCCCCCCCPPPPPPPPP
IIIIIIICCCCOOIIIIIIIIIIIIOOOOOOOOHHHHHHHHHHHEEEBBBBBBBBZZZQQZQQPPPPPPPPPPWSFFFFFFFFFFFFFFFFFFFFFPHHHHHXWWWWWWQMMMOOOOOOORRCCCCCCCCCPPPPPPPPP
IIIIICCCCCCCIIIIIIIIIIIIIIOOOOOOHHHHHHHHHHHHHEEBBBUUUUUUQQQQZQPPPPPPPPPPSWSFFFFFFFFFHFFFFFFFFFFFPHHHHXXWWWWYQQQQMOOOOOOYCCCCCCCCCCCCCPPPPPPP
IIIIIIIICCCCIIIIIIIIIIIIIIOOOOOOHHHHHHHHHHHQQQBBBBUUUUUUQQSQQQPPPPPPPPPPSSSFFFFFFFFFFFPPFPPFPPFFPPPPWWWWWYYYQQBQMOOOOOOOOPPCCCCCCCCCCCCCCPCC
IQIIIIIICCCCCIIIIIIIIIIIIOOOOOOHHHHHHHHHHHRQQQQBBBUUUUUUSSSSSSAPPPPPPPPPSSJFFFFFFFFFFFPPPPPPPPPPPPPPPPWPPPYYYQQYYLOOOOOOPPPPCCCCCCCCCCCCCCCC
QQIIIIICCCCCCCIIIIIIIIIIIICOOOOHHHHHHHHRRRRQQQQBBBUUUUUUSSSSSSPPPPPPPPSPSSJFSPPPFFFFFFPPPPPPPPPPPPPPPPPPPPPYYYYYYLPPPPPOPPPPCCCECCCCCCCCCCCC
IIIIICCCCCCCCCIIIIIIIIIIIICCOOHHHHHHHHHRRRRQQQQBBBUUUUUUSSSSSSSPSSPPPSSSSSSSSCPPFFFFFFPPPPPPPPPPPPPPPPPPPPYYYYYYUYPPPPPPPPPPPPEEECCCCCCCOOCC
IIIICCCCRRRRRRIIIIIIICCCIICCOOOHQQHHHHHHRRRRRRRBBBUUUUUUUUUSSSSSSSSSPSSSSSSSHHGPFFFFFFPPPJPPPPPJPPPPPPPYYYYYYYYYYYHPPPPPPPPPPEEEEEECCCOOOOOV
CICCCCCRRRRRRRIIMIIIIICCCCCCCOQHQQQHHRHRRRRRRRBBBBBBUUUUUUUSSSSSSSSSSSSSSSSHHHFFFFFFFFPJPJPJJJJJJPPPPPPYYYYYYYYYNPPPPPPPPPPEEEEEEEECOCOOOOOO
CICCCCCRRRCRRIRIMMIIVVCCCCCCCOQQQQQHHRRRRRRRRRNBBBBUUUUUUUUSSSSSSSSSSSSSSSSHHHHFFFFFFFJJPJJJJJJJJPPPTTTTYYYYYYYYYPPFPPPPPPPPPEEEEEEEOOOOOOOO
CCCCRRRRRRRRRRRRRMIVVCCCCICJCQQQQQQRRRRRRRRRRRNRBBBUUUUUUUUUUUUUUSSSSSSSSSSHHHHFFFFFMMJJPJJJJJJJPPPPTTTTYYYYYYYYYFFFFPPPPPPPPEETEEEOOOOOOOOO
CCCCRRRRRRRRRRRRRRVVVCCCCQQQQQQQQQQQRRRRRRRRRRNRRBBUUUUUUUUUUUUUUSSSSSSSSHHHHHHFFFFFMMJJJJJJJJJJPPTTTTTTTZYYYYYYYFFFPPQPPPPPPEOOOOOOOOOOOOOO
CCCCRRRRRRRRRRRRRRRVVVVVQQQQQQQQQQQQRRRRRRRRRRRRCCCBCUUUUUUUUUUUUSSSSSSSSHHHHHHFFFFMMMJJJJJJJJJJJPTTTTTTTZYQYFYYFFFFPQQQQQQPPOOOOOOOOOOOOOOO
CCCCRRRRRRRRRRRRRRVVVVVVQVQQQQQQQQQQQRRRRRRRRRRRCCCCCCUUUUUUUUUUUSSSSSSSHHHHHHHHHFFJJJJJJJJJJJJJTTTTTTTTTTTTFFFFFFFFQQQQQQPPPOOOOOOOOOOOOOOO
CCCCRRRRRRRRRRRRRRVRVVVVQQQQQQQQQQQQQRRRRRRRRRRRRCCCCCUUUUUUUUUUUSCTTCSHHHHHHHHHHFUJJJJJJJJJJJJJTWTTTTTTTTFFFFFFFQQQQQQQPIPPPDOOOOOOOOOOOOOO
CCCCCCRRRRRRRRRRRRRRVVVVQQQQQQQQQQQQQRRRRRRRRRRRRRCCCCCCUUUUUUUUUCCCTCHHHHHHHHHHHFUUJVJJJJWJJJJJFTTTTFTTTTFFFFFFFQQQQQQPPPPPPDOZOOKOOOOOOOOO
CCCCCCRRRRCRRRRRRVRVVVVVVVQQQQQQQQQQQRRRRRRRRRRRRRRRCCCCUUUUUUUUUCCCCCHHHHHHHHHHHFUUJJJJJJJJJJJJFFFFFFTTTFFFFFFFFFQFQQFPPPPKKKZZZZOOOOOOOOOO
CCCCCRRCCRCCRRRRRVVVVVVVVVVVQQQQQQQQQRRRRRRRRRRRRRRCCCCCUUUUUUUUUCCCOOHHHWWHHHUUUUUUJUUUUUJJJJJJFFFFFFTTFFFFFFFFFFQFFQFFKKKKKKKZZOOHHOOOOOOO
CCCCCCCCCCCCRWWRRVVVVVVVVVVVQQQQQQQQQRRRRRRRRRRRRRCCCCCCUUUUUUUUUCCCOHHHHWHHHHHUUUUUUUUUUUUJJUJJJFFFFFFFFFFFFFFFFFFFFFFFKQKKKKZZZZZOOOFOOOOO
")
```

```{r Part 1}
data = c("AAAA
BBCD
BBCC
EEEC")

data = c("OOOOO
OXOXO
OOOOO
OXOXO
OOOOO")

data = c("RRRRIICCFF
RRRRIICCCF
VVRRRCCFFF
VVRCCCJFFF
VVVVCJJCFE
VVIVCCJJEE
VVIIICJJEE
MIIIIIJJEE
MIIISIJEEE
MMMISSJEEE")

data = strsplit(data, "\n")[[1]]
data = matrix(unlist(strsplit(data, "")), byrow = T, ncol = nchar(data[1]))

sides = list(c(-1,0),c(1,0),c(0,-1),c(0,1))

findRegions = function(data, currentIndex, lookFor, test = NULL) {
  if (is.null(test)) {
    visited <<- matrix(FALSE, nrow = nrow(data), ncol = ncol(data))
    test = 1
  }

  if (visited[currentIndex[1], currentIndex[2]]) {
    return(NULL)
  }

  visited[currentIndex[1], currentIndex[2]] <<- TRUE
  
  if (data[currentIndex[1], currentIndex[2]] != lookFor) {
    return(NULL)
  }

  results = list()  
  for (side in sides){
    row = (currentIndex + side)[1]
    col = (currentIndex + side)[2]
    if (row > 0 && row <= nrow(data) && col > 0 && col <= ncol(data)) {
      result = c(results, findRegions(data, c(row,col), lookFor, visited))
      if (!is.null(result)) {
      results = c(results, result)
      }
    }
  }
  
  return(unique(append(results, list(currentIndex))))
}

findPerimeter = function(data, indexes, lookFor) {
  perimeter = 0
  indexes = as.data.frame(indexes)
  
  for (row in 1:nrow(indexes)){
    x = as.integer(indexes[row,][1])
    y = as.integer(indexes[row,][2])
    index = c(x,y)
    localPerimeter = 4
    for (side in sides){
      row = (index + side)[1]
      col = (index + side)[2]
      if (row > 0 && row <= nrow(data) && col > 0 && col <= ncol(data)) {
        if (data[row,col] == lookFor){
          localPerimeter = localPerimeter - 1
        }
      }
    }
    perimeter = perimeter + localPerimeter
  }
  return(perimeter)
}

solvePart1 = function(data) {
  price = 0
  pb = txtProgressBar(min = 0, max = length(unique(as.character(data))), style = 3)
  progress = 0
  
  for (char in unique(as.character(data))){
    regions = list()
    for (index in which(data == char)){
      row = (index - 1) %% nrow(data) + 1
      col = (index - 1) %/% nrow(data) + 1
      regions = append(regions, list(findRegions(data, c(row, col), lookFor = char)))
    }
    
    regions = lapply(regions, function(region) {
      sorted_region = do.call(rbind, region)
      sorted_region = sorted_region[order(sorted_region[, 1], sorted_region[, 2]), ]
      return(sorted_region)
    })
    
    regions = unique(regions)
    for (region in regions){
      if (length(region) == 2) {
        price = price + 4
      } else {
        perimeter = findPerimeter(data, region, lookFor = char)
        area = nrow(region)
        localprice = area * perimeter
        price = price + localprice
      }
    }
    progress = progress + 1
    setTxtProgressBar(pb, progress)
  }
  
  return(price)
}

answer = solvePart1(data)
format(answer, scientific = F)

findRegions(data, c(1,1), "W")
```

```{r Part 2}
findPerimeter = function(data, indexes, lookFor) {
  perimeter = 2
  indexes = as.data.frame(indexes)
  
  for (row in 1:nrow(indexes)){
    x = as.integer(indexes[row,][1])
    y = as.integer(indexes[row,][2])
    index = c(x,y)
    localPerimeter = 4
    for (side in sides){
      row = (index + side)[1]
      col = (index + side)[2]
      if (row > 0 && row <= nrow(data) && col > 0 && col <= ncol(data)) {
        if (data[row,col] == lookFor){
          localPerimeter = localPerimeter - 1
        }
      }
    }
    
    if (localPerimeter == 2) {
      perimeter = perimeter + 1
    }
  }
  return(perimeter)
}

findPerimeter(data, regions , "B")
regions = list(findRegions(data, c(1,1), "R"))
regions

findPerimeter2 = function(data, regions, lookFor) {
  corners = 0
  
  for (row in 1:nrow(indexes)){
    x = as.integer(indexes[row,][1])
    y = as.integer(indexes[row,][2])
    position = c(x,y)
    
    neighbours = c()
    
    for (side in sides){
      row = (position + side)[1]
      col = (position + side)[2]
      if (row > 0 && row <= nrow(data) && col > 0 && col <= ncol(data)) {
        if (data[row,col] == "R"){
          print(side)
          neighbours = c(neighbours,
                     if (all(side == c(-1, 0))) "up"
                     else if (all(side == c(1, 0))) "down"
                     else if (all(side == c(0, -1))) "left"
                     else if (all(side == c(0, 1))) "right")
        }
      } 
    }
    
    if (all(c("up","down") %in% neighbours)) 
  

  }
}

c(1,1) + sides[[1]]
```

```{r}
try = function(data, currentIndex, lookFor, test = NULL) {
  if (is.null(test)) {
    print("yes")
    visited <<- matrix(FALSE, nrow = nrow(data), ncol = ncol(data))
    test = 1
  }
  
  if (visited[currentIndex[1], currentIndex[2]]) {
    return(0) 
  }
  
  print(paste(currentIndex[1], currentIndex[2], data[currentIndex[1], currentIndex[2]]))
  if (data[currentIndex[1], currentIndex[2]] != lookFor) {
    return(1)
  }
  
  visited[currentIndex[1],currentIndex[2]] <<- T
  
  results = c()
  border = 0
  
  for (side in sides){
    row = (currentIndex + side)[1]
    col = (currentIndex + side)[2]
    if (row > 0 && row <= nrow(data) && col > 0 && col <= ncol(data)) {
      results = c(results, try(data, c(row,col), lookFor, visited))
    }
    if (row == 0 | row > nrow(data) | col == 0 | col > ncol(data)) {
      border = border + 1
    }
  }
  
  return(list(perimeter = sum(results$perimeter) + border))
}

try(data, c(1,1), "R")
rm(visited)
```


